spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://ec2-13-125-178-232.ap-northeast-2.compute.amazonaws.com:3306/withEat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: withEat
    password: withEat123!
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#        default_batch_fetch_size: 100
